name: drop_zone
description: A simple way to bring drag’n’drop to flutter web. drop_zone is commonly used for file choosing by dragging and dropping a file(s) onto a designated widget. The user can then use the dropped html file(s).
version: 1.1.0
homepage: https://github.com/Derrick56007/dropzone

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  universal_html: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
